#!/bin/bash

display_info() {
  echo "The subdomain $1 is a $2 record and points to $(dig +short $1.$3)"
}

audit_domain() {
  for subdomain in www lb-01 web-01 web-02; do
    display_info "$subdomain" "CNAME" "$1"
  done
}

audit_subdomain() {
  display_info "$2" "CNAME" "$1"
}

main() {
  [ -z "$2" ] && audit_domain "$1" || audit_subdomain "$1" "$2"
}

# Check for required arguments
[ $# -lt 1 ] && { echo "Usage: $0 <domain> [subdomain]"; exit 1; }

# Call the main function with provided arguments
main "$1" "$2"
