#!/usr/bin/env bash
#List files without numbers and dash
for file in *
do
    if [[ ! "$file" =~ ^\. ]]
    then
        new_name=$(echo "$file" | cut -d '-' -f2-)
        echo "$new_name"
    fi
done
