#!/usr/bin/env bash
# Using while loop + 9th iter = Hi
count=0
while [ "$count" -lt 10 ]
do
    if [ "$count" -eq 8 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    ((count++))
done
