#!/usr/bin/env bash
# Display numbers from 1 to 20. 4 bad luck ch, 9 bad luck japan. 17 bad luck italy.
count=1
while [ "$count" -le 20 ]
do
    echo "$count"
    case $count in
        "4)"
            echo "$count and then bad luck from China";;
        "9)"
            echo "$count and then bad luck from Japan";;
        "17)"
            echo "$count and then bad luck from Italy";;
    esac
    ((count++))
done
